<?php


namespace app\controller\home;

use think\annotation\Route;
use think\annotation\route\Group;

/**
 * Class Article
 * @package app\controller\home
 * @Group("article",ext="html");
 */
class Article extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @Route("/",method="GET");
     */
    public function index()
    {
        echo '我是article下的index';
    }
}